### ISSUE TITLE
Добавить парсер для функции преобразования карты высот

### ISSUE THREAD

**Issue by Yokud** [Yokud/OnlineTerrainGenerator#29]
### Цель

Добавить парсер для функции преобразования карты высот

### Задачи

- Реализовать класс HeightMapParser
- В классе HeightMapParser реализовать методы для парсинга Json-строки из запроса в структуру HeigthMapParams и метод для парсинга функции преобразовании карты высот из строки

### Пример работы метода парсинга функции преобразования карты высот

- Пример входных данных: "x * x + 2 * x"

- Результат: x => x * x + 2 * x

**Comment by Yokud** [comment]
https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.Scripting/

**Comment by iamshatskiy** [comment]
Выполнено
